# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('lat', models.FloatField(max_length=255, verbose_name='緯度')),
                ('long', models.FloatField(max_length=255, verbose_name='経度')),
                ('description', models.CharField(max_length=255, verbose_name='説明')),
                ('reach_count', models.IntegerField(blank=True, default=0, verbose_name='発見人数')),
            ],
        ),
    ]
