# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160808_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=255, verbose_name='ipアドレス')),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='reach_count',
        ),
        migrations.AddField(
            model_name='count',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='app.Spot', verbose_name='スポット'),
        ),
    ]
