# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160808_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='ipaddr',
            field=models.CharField(max_length=255, unique=True, verbose_name='ipアドレス'),
        ),
    ]
