# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160808_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='ipaddr',
            field=models.CharField(max_length=255, verbose_name='ipアドレス'),
        ),
    ]
